language: node_js
node_js:
  - '10'
branches:
  except:
    - gh-pages
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run coveralls
env:
  global:
    secure: RW5IDTyX7sXdQZbY6LYaFe7E0SbM2r1FN7bTeFJ682dEEg0fibstZAf64Htv7Ft671/W9QFzXLaHk7s1jXDmV6GgBIQTFl2gujqMQaS4lqp97o/I8UHPHLL514t9otZmyJO1S439U81L+qDEHOAI4O3R91o2wCbY8d8zCO2wSYZlmn9Yp29n4c1qSAbfPc/yD2dQFUy7k3wi7Q61HSXBU/CupXEUzKmzNgeOZa6YGFfCPSaRSzu1eXM1HoP/WY+Gkld/qz6M5uU0xMjBjN3e1ff0L687z/2PaJXjqGIK6nTCMwBsme5i7Cfp6KgvddfMgGr47ZyTsLIlojExT52HeeZ2flv1jDtaDg/UilJ7/Z07tBaqd1KBC+chx/3VEtuwuyxUWGrR4NF0/DI0YBoZekSxHbk2JbrT3gNmqt+N/qJty2onwB8omxBa+RzoKWfcpawtR2Sn9SAiwP/nzi9VOxuqQpoVu1QF52kq+cOXuOLx9tJ4ijcP+2vsyQxdJW7j/mZ5sjz30QUsdfGuGtO6TJLAO9a4H7+69pAMe30T1UHVqj8kPWnsd18Sb9WAJ0cL5wizs0U71Xnlji/hI+NNKay/00zpnkrF7t4owvSZ/ORFeKnJuoQaTM7YJpKIXdkq6K/YxD+GNMCyg/+dRWQxP05+6uZcKHv1yw4auZkBHB0=
